### ISSUE TITLE
Crash on startup on Windows due to StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by henrygouk** [Waikato/moa#133]
The following error happens on startup on Windows 10.

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
        at java.base/java.lang.StringLatin1.charAt(Unknown Source)
        at java.base/java.lang.String.charAt(Unknown Source)
        at moa.DoTask.isJavaVersionOK(DoTask.java:61)
        at moa.gui.GUI.main(GUI.java:78)
```

**Comment by henrygouk** [comment]
I've managed to track it down to `System.getProperty("java.version")` returning `"10"`
