### ISSUE TITLE
Recommender system example throws exception

### ISSUE THREAD

**Issue by henrygouk** [Waikato/moa#155]
I get the following error when trying to run the recommender system [example](https://moa.cms.waikato.ac.nz/details/recommender-systems/) using code in master.

```Failure reason: class java.lang.String cannot be cast to class moa.evaluation.preview.Preview (java.lang.String is in module java.base of loader 'bootstrap'; moa.evaluation.preview.Preview is in unnamed module of loader 'app')
*** STACK TRACE ***java.lang.ClassCastException: class java.lang.String cannot be cast to class moa.evaluation.preview.Preview (java.lang.String is in module java.base of loader 'bootstrap'; moa.evaluation.preview.Preview is in unnamed module of loader 'app')
	at moa.gui.PreviewPanel.setLatestPreview(PreviewPanel.java:171)
	at moa.gui.PreviewPanel.setTaskThreadToPreview(PreviewPanel.java:144)
	at moa.gui.PreviewPanel.latestPreviewChanged(PreviewPanel.java:220)
	at moa.tasks.StandardTaskMonitor.setLatestResultPreview(StandardTaskMonitor.java:141)
	at moa.tasks.EvaluateOnlineRecommender.doMainTask(EvaluateOnlineRecommender.java:128)
	at moa.tasks.MainTask.doTaskImpl(MainTask.java:50)
	at moa.tasks.AbstractTask.doTask(AbstractTask.java:57)
	at moa.tasks.TaskThread.run(TaskThread.java:76)
```

**Comment by henrygouk** [comment]
Running from the command line is successful. This is possibly something to do with #146?

**Comment by abifet** [comment]
Yes, it may be. Is it solved now?
