### ISSUE TITLE
Cannot handle numeric class

### ISSUE THREAD

**Issue by haokeliu** [Waikato/moa#169]
Hi:
   I made an error when using MOA to learn the Flags.arff dataset incremental: 
weka.core.UnsupportedAttributeTypeException: weka.classifiers.trees.HoeffdingTree: Cannot handle numeric class!
 The command line is：EvaluatePrequentialMultiTarget -l (multilabel.MEKAClassifier -l (meka.classifiers.multilabel.incremental.BRUpdateable -W weka.classifiers.trees.HoeffdingTree -- -L 2 -S 1 -E 1.0E-7 -H 0.05 -M 0.01 -G 200.0 -N 0.0)) -s (MultiTargetArffFileStream -f (E:\Program Files\multi-Label\dataset\Real\Flags.arff) -c -7) -e BasicMultiLabelPerformanceEvaluator
Detailed error information：
{M}assive {O}nline {A}nalysis
Version:  18.06 June 2018
Copyright: (C) 2007-2018 University of Waikato, Hamilton, New Zealand
Web: http://moa.cms.waikato.ac.nz/

[WARNING] Only 0 labels found! (Expecting 7)
 (Ignoring this prediction)
三月 21, 2019 2:43:45 下午 com.github.fommil.netlib.ARPACK <clinit>
警告: Failed to load implementation from: com.github.fommil.netlib.NativeSystemARPACK
三月 21, 2019 2:43:45 下午 com.github.fommil.jni.JniLoader liberalLoad
信息: successfully loaded C:\Users\芝士\AppData\Local\Temp\jniloader7654186575430500792netlib-native_ref-win-x86_64.dll
[ERROR] Failed to build classifier, L=7
weka.core.UnsupportedAttributeTypeException: weka.classifiers.trees.HoeffdingTree: Cannot handle numeric class!
	at weka.core.Capabilities.test(Capabilities.java:1067)
	at weka.core.Capabilities.test(Capabilities.java:1256)
	at weka.core.Capabilities.test(Capabilities.java:1138)
	at weka.core.Capabilities.testWithFail(Capabilities.java:1468)
	at weka.classifiers.trees.HoeffdingTree.buildClassifier(HoeffdingTree.java:751)
	at meka.classifiers.multilabel.BR.buildClassifier(BR.java:75)
	at moa.classifiers.multilabel.MEKAClassifier.trainOnInstanceImpl(MEKAClassifier.java:107)
	at moa.classifiers.AbstractMultiLabelLearner.trainOnInstanceImpl(AbstractMultiLabelLearner.java:20)
	at moa.classifiers.AbstractClassifier.trainOnInstance(AbstractClassifier.java:178)
	at moa.classifiers.AbstractClassifier.trainOnInstance(AbstractClassifier.java:249)
	at moa.tasks.EvaluatePrequentialMultiTarget.doMainTask(EvaluatePrequentialMultiTarget.java:211)
	at moa.tasks.MainTask.doTaskImpl(MainTask.java:50)
	at moa.tasks.AbstractTask.doTask(AbstractTask.java:57)
	at moa.tasks.TaskThread.run(TaskThread.java:76)
[WARNING] Failed to get votes from multi-label classifier (not trained yet?).
Can you help me?

**Comment by abifet** [comment]
It seems that you're using the WEKA implementation of Hoeffding Tree, instead of the MOA one.
