### ISSUE TITLE
Tests on Regressors are failing

### ISSUE THREAD

**Issue by nuwangunasekara** [Waikato/moa#294]
The tests run with  ```mvn clean package``` on Regressors are failing due to 73cb667c855f26ff018afbdd01e337e8e162bd6a 
(which introduced coefficient of determination and adjusted coefficient of determination to Basic and Window Regression Performance Evaluators).

```
git reflog
2ff8dcf7 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: clone: from https://github.com/Waikato/moa.git
```

```
 mvn clean package
:
:
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running moa.integration.SimpleClusterTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.257 sec - in moa.integration.SimpleClusterTest
Running moa.streams.filters.SelectAttributesFilterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.048 sec - in moa.streams.filters.SelectAttributesFilterTest
Running moa.classifiers.trees.EFDTTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by sizeof.agent.SizeOfAgent (file:/Users/ng98/.m2/repository/com/github/fracpete/sizeofag/1.1.0/sizeofag-1.1.0.jar) to field java.util.ArrayList.elementData
WARNING: Please consider reporting this to the maintainers of sizeof.agent.SizeOfAgent
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.022 sec - in moa.classifiers.trees.EFDTTest
Running moa.classifiers.trees.DecisionStumpTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.528 sec - in moa.classifiers.trees.DecisionStumpTest
Running moa.classifiers.trees.FIMTDDTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.123 sec <<< FAILURE! - in moa.classifiers.trees.FIMTDDTest
testRegression(moa.classifiers.trees.FIMTDDTest)  Time elapsed: 0.12 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Output differs:
13a14,15
>   coefficient of determination: -3.69585407
>   adjusted coefficient of determination: -4.17071572
27a30,31
>   coefficient of determination: -4.45694154
>   adjusted coefficient of determination: -4.7167959
41a46,47
>   coefficient of determination: -3.87113732
>   adjusted coefficient of determination: -4.02283364
55a62,63
>   coefficient of determination: -2.95974065
>   adjusted coefficient of determination: -3.05135418
69a78,79
>   coefficient of determination: -2.63190591
>   adjusted coefficient of determination: -2.69875081
83a94,95
>   coefficient of determination: -2.07176614
>   adjusted coefficient of determination: -2.11870315
97a110,111
>   coefficient of determination: -1.9344547
>   adjusted coefficient of determination: -1.97278575
111a126,127
>   coefficient of determination: -1.72533595
>   adjusted coefficient of determination: -1.75642343
125a142,143
>   coefficient of determination: -1.63857809
>   adjusted coefficient of determination: -1.66529036
139a158,159
>   coefficient of determination: -1.46802168
>   adjusted coefficient of determination: -1.49048093

	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertNull(Assert.java:277)
	at junit.framework.TestCase.assertNull(TestCase.java:418)
	at moa.classifiers.AbstractClassifierTestCase.testRegression(AbstractClassifierTestCase.java:350)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at moa.test.MoaTestCase.runTest(MoaTestCase.java:137)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running moa.classifiers.trees.HoeffdingAdaptiveTreeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.47 sec - in moa.classifiers.trees.HoeffdingAdaptiveTreeTest
Running moa.classifiers.trees.RandomHoeffdingTreeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.631 sec - in moa.classifiers.trees.RandomHoeffdingTreeTest
Running moa.classifiers.trees.HoeffdingOptionTreeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.233 sec - in moa.classifiers.trees.HoeffdingOptionTreeTest
Running moa.classifiers.trees.ORTOTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.096 sec <<< FAILURE! - in moa.classifiers.trees.ORTOTest
testRegression(moa.classifiers.trees.ORTOTest)  Time elapsed: 0.088 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Output differs:
13a14,15
>   coefficient of determination: -3.69585407
>   adjusted coefficient of determination: -4.17071572
30a33,34
>   coefficient of determination: -4.45694154
>   adjusted coefficient of determination: -4.7167959
47a52,53
>   coefficient of determination: -4.13259034
>   adjusted coefficient of determination: -4.29242879
64a71,72
>   coefficient of determination: -3.60318141
>   adjusted coefficient of determination: -3.70968175
81a90,91
>   coefficient of determination: -3.54611568
>   adjusted coefficient of determination: -3.62978652
98a109,110
>   coefficient of determination: -3.04385015
>   adjusted coefficient of determination: -3.10564073
115a128,129
>   coefficient of determination: -3.00328047
>   adjusted coefficient of determination: -3.05557295
132a147,148
>   coefficient of determination: -3.4569076
>   adjusted coefficient of determination: -3.50774685
149a166,167
>   coefficient of determination: -3.3922293
>   adjusted coefficient of determination: -3.43669507
166a185,186
>   coefficient of determination: -3.40905363
>   adjusted coefficient of determination: -3.44917647

	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertNull(Assert.java:277)
	at junit.framework.TestCase.assertNull(TestCase.java:418)
	at moa.classifiers.AbstractClassifierTestCase.testRegression(AbstractClassifierTestCase.java:350)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at moa.test.MoaTestCase.runTest(MoaTestCase.java:137)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running moa.classifiers.trees.ASHoeffdingTreeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.998 sec - in moa.classifiers.trees.ASHoeffdingTreeTest
Running moa.classifiers.trees.LimAttHoeffdingTreeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.439 sec - in moa.classifiers.trees.LimAttHoeffdingTreeTest
Running moa.classifiers.trees.AdaHoeffdingOptionTreeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.2 sec - in moa.classifiers.trees.AdaHoeffdingOptionTreeTest
Running moa.classifiers.trees.HoeffdingTreeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.647 sec - in moa.classifiers.trees.HoeffdingTreeTest
Running moa.classifiers.deeplearning.CANDTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 64.573 sec - in moa.classifiers.deeplearning.CANDTest
Running moa.classifiers.deeplearning.MLPTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 39.2 sec - in moa.classifiers.deeplearning.MLPTest
Running moa.classifiers.meta.imbalanced.OnlineAdaC2Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.807 sec - in moa.classifiers.meta.imbalanced.OnlineAdaC2Test
Running moa.classifiers.meta.imbalanced.OnlineCSB2Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.834 sec - in moa.classifiers.meta.imbalanced.OnlineCSB2Test
Running moa.classifiers.meta.imbalanced.OnlineAdaBoostTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.691 sec - in moa.classifiers.meta.imbalanced.OnlineAdaBoostTest
Running moa.classifiers.meta.imbalanced.RebalanceStreamTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.112 sec - in moa.classifiers.meta.imbalanced.RebalanceStreamTest
Running moa.classifiers.meta.imbalanced.OnlineRUSBoostTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.845 sec - in moa.classifiers.meta.imbalanced.OnlineRUSBoostTest
Running moa.classifiers.meta.imbalanced.CSMOTETest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.403 sec - in moa.classifiers.meta.imbalanced.CSMOTETest
Running moa.classifiers.meta.imbalanced.OnlineSMOTEBaggingTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 326.8 sec - in moa.classifiers.meta.imbalanced.OnlineSMOTEBaggingTest
Running moa.classifiers.meta.imbalanced.OnlineUnderOverBaggingTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.651 sec - in moa.classifiers.meta.imbalanced.OnlineUnderOverBaggingTest
Running moa.classifiers.meta.OzaBagTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.25 sec - in moa.classifiers.meta.OzaBagTest
Running moa.classifiers.meta.StreamingRandomPatchesTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.266 sec - in moa.classifiers.meta.StreamingRandomPatchesTest
Running moa.classifiers.meta.ADOBTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.435 sec - in moa.classifiers.meta.ADOBTest
Running moa.classifiers.meta.WEKAClassifierTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.478 sec - in moa.classifiers.meta.WEKAClassifierTest
Running moa.classifiers.meta.OzaBoostAdwinTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.807 sec - in moa.classifiers.meta.OzaBoostAdwinTest
Running moa.classifiers.meta.AdaptiveRandomForestTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.678 sec - in moa.classifiers.meta.AdaptiveRandomForestTest
Running moa.classifiers.meta.LeveragingBagTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.985 sec - in moa.classifiers.meta.LeveragingBagTest
Running moa.classifiers.meta.DynamicWeightedMajorityTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.966 sec - in moa.classifiers.meta.DynamicWeightedMajorityTest
Running moa.classifiers.meta.OzaBagASHTTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.495 sec - in moa.classifiers.meta.OzaBagASHTTest
Running moa.classifiers.meta.LimAttClassifierTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.16 sec - in moa.classifiers.meta.LimAttClassifierTest
Running moa.classifiers.meta.OzaBoostTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.123 sec - in moa.classifiers.meta.OzaBoostTest
Running moa.classifiers.meta.BOLETest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.407 sec - in moa.classifiers.meta.BOLETest
Running moa.classifiers.meta.HeterogeneousEnsembleBlastTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 49.882 sec - in moa.classifiers.meta.HeterogeneousEnsembleBlastTest
Running moa.classifiers.meta.AccuracyUpdatedEnsembleTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.388 sec - in moa.classifiers.meta.AccuracyUpdatedEnsembleTest
Running moa.classifiers.meta.OCBoostTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.944 sec - in moa.classifiers.meta.OCBoostTest
Running moa.classifiers.meta.AccuracyWeightedEnsembleTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.966 sec - in moa.classifiers.meta.AccuracyWeightedEnsembleTest
Running moa.classifiers.meta.TemporallyAugmentedClassifierTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.074 sec - in moa.classifiers.meta.TemporallyAugmentedClassifierTest
Running moa.classifiers.meta.WeightedMajorityAlgorithmTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.832 sec - in moa.classifiers.meta.WeightedMajorityAlgorithmTest
Running moa.classifiers.meta.SelfOptimisingKNearestLeavesTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.375 sec - in moa.classifiers.meta.SelfOptimisingKNearestLeavesTest
Running moa.classifiers.meta.OnlineAccuracyUpdatedEnsembleTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.115 sec - in moa.classifiers.meta.OnlineAccuracyUpdatedEnsembleTest
Running moa.classifiers.meta.OzaBagAdwinTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.932 sec - in moa.classifiers.meta.OzaBagAdwinTest
Running moa.classifiers.bayes.NaiveBayesTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.442 sec - in moa.classifiers.bayes.NaiveBayesTest
Running moa.classifiers.bayes.NaiveBayesMultinomialTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.484 sec - in moa.classifiers.bayes.NaiveBayesMultinomialTest
Running moa.classifiers.drift.DriftDetectionMethodClassifierTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.594 sec - in moa.classifiers.drift.DriftDetectionMethodClassifierTest
Running moa.classifiers.drift.SingleClassifierDriftTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.581 sec - in moa.classifiers.drift.SingleClassifierDriftTest
Running moa.classifiers.rules.core.UtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in moa.classifiers.rules.core.UtilsTest
Running moa.classifiers.rules.multilabel.AMRulesMultiTargetRegressorSemiSuperTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.285 sec <<< FAILURE! - in moa.classifiers.rules.multilabel.AMRulesMultiTargetRegressorSemiSuperTest
testRegression(moa.classifiers.rules.multilabel.AMRulesMultiTargetRegressorSemiSuperTest)  Time elapsed: 0.281 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Output differs:
13a14,15
>   coefficient of determination: -0.00378039
>   adjusted coefficient of determination: -0.10528628
31a34,35
>   coefficient of determination: 0.0090925
>   adjusted coefficient of determination: -0.03809357
49a54,55
>   coefficient of determination: 0.0456825
>   adjusted coefficient of determination: 0.01596327
67a74,75
>   coefficient of determination: 0.08258003
>   adjusted coefficient of determination: 0.06135438
85a94,95
>   coefficient of determination: 0.10857232
>   adjusted coefficient of determination: 0.09216568
103a114,115
>   coefficient of determination: 0.12464748
>   adjusted coefficient of determination: 0.11127198
121a134,135
>   coefficient of determination: 0.15561196
>   adjusted coefficient of determination: 0.14458221
139a154,155
>   coefficient of determination: 0.06851541
>   adjusted coefficient of determination: 0.05789011
157a174,175
>   coefficient of determination: 0.08028747
>   adjusted coefficient of determination: 0.07097655
175a194,195
>   coefficient of determination: 0.06795483
>   adjusted coefficient of determination: 0.05947312

	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertNull(Assert.java:277)
	at junit.framework.TestCase.assertNull(TestCase.java:418)
	at moa.classifiers.AbstractClassifierTestCase.testRegression(AbstractClassifierTestCase.java:350)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at moa.test.MoaTestCase.runTest(MoaTestCase.java:137)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running moa.classifiers.rules.multilabel.core.voting.FirstHitVoteMultiLabelTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in moa.classifiers.rules.multilabel.core.voting.FirstHitVoteMultiLabelTest
Running moa.classifiers.rules.multilabel.core.voting.InverseErrorWeightedVoteMultiLabelTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in moa.classifiers.rules.multilabel.core.voting.InverseErrorWeightedVoteMultiLabelTest
Running moa.classifiers.rules.multilabel.core.voting.UniformWeightedVoteMultiLabelTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in moa.classifiers.rules.multilabel.core.voting.UniformWeightedVoteMultiLabelTest
Running moa.classifiers.rules.multilabel.instancetransformers.InstanceOutputAttributesSelectorTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in moa.classifiers.rules.multilabel.instancetransformers.InstanceOutputAttributesSelectorTest
Running moa.classifiers.rules.multilabel.errormeasurers.RelativeMeanAbsoluteDeviationMTTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in moa.classifiers.rules.multilabel.errormeasurers.RelativeMeanAbsoluteDeviationMTTest
Running moa.classifiers.rules.multilabel.errormeasurers.RelativeRootMeanSquaredErrorMTTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in moa.classifiers.rules.multilabel.errormeasurers.RelativeRootMeanSquaredErrorMTTest
Running moa.classifiers.rules.RuleClassifierTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.526 sec - in moa.classifiers.rules.RuleClassifierTest
Running moa.classifiers.rules.AMRulesRegressorTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.174 sec <<< FAILURE! - in moa.classifiers.rules.AMRulesRegressorTest
testRegression(moa.classifiers.rules.AMRulesRegressorTest)  Time elapsed: 0.17 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Output differs:
13a14,15
>   coefficient of determination: -0.00378039
>   adjusted coefficient of determination: -0.10528628
31a34,35
>   coefficient of determination: 0.0090925
>   adjusted coefficient of determination: -0.03809357
49a54,55
>   coefficient of determination: 0.0456825
>   adjusted coefficient of determination: 0.01596327
67a74,75
>   coefficient of determination: 0.08258003
>   adjusted coefficient of determination: 0.06135438
85a94,95
>   coefficient of determination: 0.10857232
>   adjusted coefficient of determination: 0.09216568
103a114,115
>   coefficient of determination: 0.12464748
>   adjusted coefficient of determination: 0.11127198
121a134,135
>   coefficient of determination: 0.15561196
>   adjusted coefficient of determination: 0.14458221
139a154,155
>   coefficient of determination: 0.06851541
>   adjusted coefficient of determination: 0.05789011
157a174,175
>   coefficient of determination: 0.08028747
>   adjusted coefficient of determination: 0.07097655
175a194,195
>   coefficient of determination: 0.06795483
>   adjusted coefficient of determination: 0.05947312

	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertNull(Assert.java:277)
	at junit.framework.TestCase.assertNull(TestCase.java:418)
	at moa.classifiers.AbstractClassifierTestCase.testRegression(AbstractClassifierTestCase.java:350)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at moa.test.MoaTestCase.runTest(MoaTestCase.java:137)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running moa.classifiers.rules.RuleClassifierNBayesTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.064 sec - in moa.classifiers.rules.RuleClassifierNBayesTest
Running moa.classifiers.functions.SPegasosTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.412 sec - in moa.classifiers.functions.SPegasosTest
Running moa.classifiers.functions.PerceptronTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.443 sec - in moa.classifiers.functions.PerceptronTest
Running moa.classifiers.functions.SGDTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.436 sec - in moa.classifiers.functions.SGDTest
Running moa.classifiers.functions.MajorityClassTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.388 sec - in moa.classifiers.functions.MajorityClassTest
Running moa.classifiers.functions.NoChangeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.42 sec - in moa.classifiers.functions.NoChangeTest
Running moa.classifiers.active.ALUncertaintyTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.934 sec - in moa.classifiers.active.ALUncertaintyTest
Running moa.classifiers.active.ALRandomTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.553 sec - in moa.classifiers.active.ALRandomTest
Running com.yahoo.labs.samoa.instances.MultiTargetArffLoaderTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.yahoo.labs.samoa.instances.MultiTargetArffLoaderTest

Results :

Failed tests: 
  FIMTDDTest>MoaTestCase.runTest:137->AbstractClassifierTestCase.testRegression:350 Output differs:
13a14,15
>   coefficient of determination: -3.69585407
>   adjusted coefficient of determination: -4.17071572
27a30,31
>   coefficient of determination: -4.45694154
>   adjusted coefficient of determination: -4.7167959
41a46,47
>   coefficient of determination: -3.87113732
>   adjusted coefficient of determination: -4.02283364
55a62,63
>   coefficient of determination: -2.95974065
>   adjusted coefficient of determination: -3.05135418
69a78,79
>   coefficient of determination: -2.63190591
>   adjusted coefficient of determination: -2.69875081
83a94,95
>   coefficient of determination: -2.07176614
>   adjusted coefficient of determination: -2.11870315
97a110,111
>   coefficient of determination: -1.9344547
>   adjusted coefficient of determination: -1.97278575
111a126,127
>   coefficient of determination: -1.72533595
>   adjusted coefficient of determination: -1.75642343
125a142,143
>   coefficient of determination: -1.63857809
>   adjusted coefficient of determination: -1.66529036
139a158,159
>   coefficient of determination: -1.46802168
>   adjusted coefficient of determination: -1.49048093

  ORTOTest>MoaTestCase.runTest:137->AbstractClassifierTestCase.testRegression:350 Output differs:
13a14,15
>   coefficient of determination: -3.69585407
>   adjusted coefficient of determination: -4.17071572
30a33,34
>   coefficient of determination: -4.45694154
>   adjusted coefficient of determination: -4.7167959
47a52,53
>   coefficient of determination: -4.13259034
>   adjusted coefficient of determination: -4.29242879
64a71,72
>   coefficient of determination: -3.60318141
>   adjusted coefficient of determination: -3.70968175
81a90,91
>   coefficient of determination: -3.54611568
>   adjusted coefficient of determination: -3.62978652
98a109,110
>   coefficient of determination: -3.04385015
>   adjusted coefficient of determination: -3.10564073
115a128,129
>   coefficient of determination: -3.00328047
>   adjusted coefficient of determination: -3.05557295
132a147,148
>   coefficient of determination: -3.4569076
>   adjusted coefficient of determination: -3.50774685
149a166,167
>   coefficient of determination: -3.3922293
>   adjusted coefficient of determination: -3.43669507
166a185,186
>   coefficient of determination: -3.40905363
>   adjusted coefficient of determination: -3.44917647

  AMRulesMultiTargetRegressorSemiSuperTest>MoaTestCase.runTest:137->AbstractClassifierTestCase.testRegression:350 Output differs:
13a14,15
>   coefficient of determination: -0.00378039
>   adjusted coefficient of determination: -0.10528628
31a34,35
>   coefficient of determination: 0.0090925
>   adjusted coefficient of determination: -0.03809357
49a54,55
>   coefficient of determination: 0.0456825
>   adjusted coefficient of determination: 0.01596327
67a74,75
>   coefficient of determination: 0.08258003
>   adjusted coefficient of determination: 0.06135438
85a94,95
>   coefficient of determination: 0.10857232
>   adjusted coefficient of determination: 0.09216568
103a114,115
>   coefficient of determination: 0.12464748
>   adjusted coefficient of determination: 0.11127198
121a134,135
>   coefficient of determination: 0.15561196
>   adjusted coefficient of determination: 0.14458221
139a154,155
>   coefficient of determination: 0.06851541
>   adjusted coefficient of determination: 0.05789011
157a174,175
>   coefficient of determination: 0.08028747
>   adjusted coefficient of determination: 0.07097655
175a194,195
>   coefficient of determination: 0.06795483
>   adjusted coefficient of determination: 0.05947312

  AMRulesRegressorTest>MoaTestCase.runTest:137->AbstractClassifierTestCase.testRegression:350 Output differs:
13a14,15
>   coefficient of determination: -0.00378039
>   adjusted coefficient of determination: -0.10528628
31a34,35
>   coefficient of determination: 0.0090925
>   adjusted coefficient of determination: -0.03809357
49a54,55
>   coefficient of determination: 0.0456825
>   adjusted coefficient of determination: 0.01596327
67a74,75
>   coefficient of determination: 0.08258003
>   adjusted coefficient of determination: 0.06135438
85a94,95
>   coefficient of determination: 0.10857232
>   adjusted coefficient of determination: 0.09216568
103a114,115
>   coefficient of determination: 0.12464748
>   adjusted coefficient of determination: 0.11127198
121a134,135
>   coefficient of determination: 0.15561196
>   adjusted coefficient of determination: 0.14458221
139a154,155
>   coefficient of determination: 0.06851541
>   adjusted coefficient of determination: 0.05789011
157a174,175
>   coefficient of determination: 0.08028747
>   adjusted coefficient of determination: 0.07097655
175a194,195
>   coefficient of determination: 0.06795483
>   adjusted coefficient of determination: 0.05947312


Tests run: 157, Failures: 4, Errors: 0, Skipped: 0
```

**Comment by nuwangunasekara** [comment]
Fixed in PR #300
